channels:
- conda-forge
dependencies:
- python=3.12.11
- pip<=25.1
- pip:
  - mlflow==2.22.0
  - numpy==2.2.5
  - pandas==2.2.3
  - scikit-learn==1.6.1
  - scipy==1.15.3
  - xgboost==3.0.2
name: mlflow-env
