# Dockerfile
FROM python:3.10-slim

RUN pip install --no-cache-dir \
    mlflow==2.13.2 \
    sagemaker-mlflow==0.1.0 \
    xgboost==2.1.4 \
    boto3 \
    numpy \
    pandas \
    awswrangler==2.20.0
