name: CI/CD for Training Pipeline

on:
  push:
    branches:
      - feature/aws

jobs:
  training-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r operation/batch_training/requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-2

      - name: Create training pipeline
        run: python operation/batch_training/training_pipeline.py
        env:
          GITHUB_ACTOR: ${{ github.actor }}